titleAndCommits: true
allowMergeCommits: true
allowRevertCommits: true

types:
  - "feat"
  - "fix"
  - "docs"
  - "style"
  - "refactor"
  - "perf"
  - "test"
  - "revert"
  - "version"

scopes:
  - "admin"
  - "cli"
  - "destination"
  - "errors"
  - "flow"
  - "gateway"
  - "logger"
  - "pubsub"
  - "scheduler"
  - "source"
  - "supervisor"
  - "store"
  - "wanderer"
