package destination

import (
	"github.com/nunchistudio/blacksmith/adapter/supervisor"

	"github.com/sirupsen/logrus"
)

/*
Toolkit contains a suite of utilities and data to help the user successfully run
the destination functions.
*/
type Toolkit struct {

	// Logger gives access to the logrus Logger passed in options when creating the
	// Blacksmith application.
	Logger *logrus.Logger

	// Service represents the instance of the service registered in the supervisor
	// and currently processing the action. It is an instance of the gateway service
	// when Marshaling the action, and an instance of the scheduler service when
	// Loading the action into the destination.
	//
	// Note: This is nil when there is no supervisor adapter configured.
	Service *supervisor.Service

	// EventID is the unique identifier of the event generated by the gateway and
	// that is related to the job being marshaled.
	//
	// Note: This is not applicable when using the Load function, since it receives
	// a queue of events and related jobs to execute.
	//
	// Example: "1UYc8EebLqCAFMOSkbYZdJwNLAJ"
	EventID string

	// JobID is the unique identifier of the job generated by the scheduler and
	// that is being marshaled.
	//
	// Note: This is not applicable when using the Load function, since it receives
	// a queue of events and related jobs to execute.
	//
	// Example: "1UYc8EebLqCAFMOSkbYZdJwNLAJ"
	JobID string
}
